### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-api-docs#1]
@talltom are these ready to be deployed, and if so, where to? Let me know and I can set this up. Note that I will be using codepipeline and codebuild for this; it is much tidier than using jenkins and eventually I would like to migrate everything off of jenkins (which then saves on running costs).

**Comment by tomasholderness** [comment]
These are deployed to the [gh-pages](https://github.com/urbanriskmap/cognicity-api-docs/tree/gh-pages) branch of this repo, and are available at https://urbanriskmap.github.io/cognicity-api-docs/

Deployment to the gh-pages branch from builds on master is done via Travis.
